name: Coverage

on: [pull_request, push]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-24.04
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Populate cache
        uses: ./.github/workflows/cache

      - run: sudo apt-get install -y squashfs-tools

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@e8c64729e2a2a2c3cfa6751fa496b34ca19f390c # cargo-llvm-cov

      # generate release builds of the testable binaries
      # this is meant to actually run the binary, so this will fail but the binary will be built
      - run: cargo llvm-cov run --bin replace-backhand --no-clean --release || true
      - run: cargo llvm-cov run --bin add-backhand --no-clean --release || true
      - run: cargo llvm-cov run --bin unsquashfs-backhand --no-clean --release || true

      # run coverage on tests
      - run: cargo llvm-cov --workspace --codecov --output-path codecov.json --features __test_unsquashfs --release --no-clean -- --skip slow

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true
