on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule: [cron: "40 1 * * *"]

name: Check MSRV of backhand
jobs:
  build-test-backhand:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        toolchain:
            # msrv of backhand
          - 1.72.1

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Populate cache
        uses: ./.github/workflows/cache

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo +${{ matrix.toolchain }} check --locked -p backhand

  build-test-backhand-cli:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        toolchain:
            # msrv of backhand-cli
          - 1.77

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Populate cache
        uses: ./.github/workflows/cache

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo +${{ matrix.toolchain }} check --locked -p backhand-cli
